name: 'unity-build-github-action'
description: 'This action performs a Unity command line build.'
inputs:
  project-directory:
    description: >
      Open the project at the given path. If the pathname contains spaces, enclose it in quotes.
    required: true
  unity-version:
    description: >
      Specify the Unity version to be used.
      If omitted, the project version is used.
    required: false
    default: ''
  build-target:
    description: >
      Allows the selection of an active build target before loading a project.
      
      Possible options are:
      Standalone, Win, Win64, OSXUniversal, Linux, Linux64, LinuxUniversal, iOS, Android, Web, WebStreamed, WebGL, XboxOne, PS4, WindowsStoreApps, Switch, N3DS, tvOS.
    required: true
  configuration:
    description: >
      The configuration to use when building the app.
      Defaults to 'Debug'

      Possible options are:
      Debug, Release.
    required: false
    default: 'Debug'
  output-directory:
    description: >
      Specifies the output directory.
      Defaults to $RUNNER_TEMP
    required: false
    default: ${{ runner.temp }}
  output-name:
    description: >
      Specifies the output file name.
      If an empty string is passed for this value, the product name or "ProductName" specified in the Unity Editor will be used.
      Defaults to "Build"
    required: false
    default: 'Build'
  execute-method:
    description: >
      Execute the static method as soon as Unity opens the project,
      and after the optional Asset server update is complete.
    required: false
    default: ''
  log-file:
    description: >
      Specify where Unity writes the Editor or Windows/Linux/OSX standalone log file.
      To output to the console, specify - for the path name.
      On Windows, specify - option to make the output go to stdout, which is not the console by default.
    required: false
    default: '-'
  additional-arguments:
    description: >
      Specify additional required arguments.
    required: false
    default: ''
  export-method:
    description: >
      Define the profile type,
      can be appstore, adhoc, development, enterprise, developer_id, mac_installer_distribution

      Required for iOS builds.
    required: false
    default: 'development'
  include-bitcode:
    description: >
      Should the ipa file include bitcode?
      Defaults to false.

      Required for iOS builds.
    required: false
    default: false
  include-symbols:
    description: >
      Should the ipa file include symbols?
      Defaults to false.

      Required for iOS builds.
    required: false
    default: false
  provisioning-profile-base64:
    description: ''
    required: false
    default: ''
  provisioning-profile-uuid:
    description: >
      Specify the UUID of the provisioning profile.
      Required for iOS builds.
    required: false
    default: ''
  team-id:
    description: >
      The ID of your Developer Portal team if you're in multiple teams.
      Required for iOS builds.
    required: false
    default: ''
  keystore:
    description: >
      Specify the path to the keystore file.
      For Android, if `keystore` or `keystore-base64`, `keystore-password`, `keystore-alias`,
      `keystore-alias-password` is not specified, will be signed with a debug key.

      Required for Android builds.
    required: false
    default: ''
  keystore-base64:
    description: >
      Specifies Base64 data for the keystore.
      If you do not specify a file path in `keystore`, you must specify this parameter.
      Also, if this value is specified, the value of `keystore` is ignored.

      Required for Android builds.
    required: false
    default: ''
  keystore-password:
    description: >
      Specify the password for the keystore.

      Required for Android builds.
    required: false
    default: ''
  keystore-alias:
    description: >
      Specifies the name of the keystore alias.

      Required for Android builds.
    required: false
    default: ''
  keystore-alias-password:
    description: >
      Specify the password for the keystore alias.

      Required for Android builds.
    required: false
    default: ''
  temporary-directory:
    description: >
      Specify a temporary folder for the Xcode project files that Unity outputs during iOS build.
      No change is required unless there is a specific reason.
    required: false
    default: ${{ runner.temp }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "box"
  color: "orange"