name: 'Unity Build'
description: 'This action performs a Unity command line build.'
inputs:
  app-id:
    description: >
      Specify the App ID.

      ex) com.akiojin.Sample
    required: true
  project-directory:
    description: >
      Open the project at the given path. If the pathname contains spaces, enclose it in quotes.
    required: false
    default: ${{ github.workspace }}
  unity-version:
    description: >
      Specify the Unity version to be used.
      If omitted, the project version is used.
    required: false
    default: ''
  build-target:
    description: >
      Allows the selection of an active build target before loading a project.
      
      Possible options are:
      Standalone, Win, Win64, OSXUniversal, Linux, Linux64, LinuxUniversal, iOS, Android, Web, WebStreamed, WebGL, XboxOne, PS4, WindowsStoreApps, Switch, N3DS, tvOS.
    required: true
  revision:
    description: >
      Specify the revision.
      This value is set to PlayerSettings.iOS.buildNumber or PlayerSettings.Android.bundleVersionCode.
      If omitted, github.run_number is set.
    required: false
    default: ${{ github.run_number }}
  configuration:
    description: >
      The configuration to use when building the app.
      Defaults to 'Debug'

      Possible options are:
      Debug, Release.
    required: false
    default: 'Debug'
  output-directory:
    description: >
      Specifies the output directory.
      If omitted, runner.temp is set.
    required: false
    default: ${{ runner.temp }}
  output-name:
    description: >
      Specifies the output file name.
      If an empty string is passed for this value, the product name or "ProductName" specified in the Unity Editor will be used.
      Defaults to "Build"
    required: false
    default: 'Build'
  execute-method:
    description: >
      Execute the static method as soon as Unity opens the project,
      and after the optional Asset server update is complete.
    required: false
    default: ''
  install-directory:
    description: >
      If the Unity installation location is not the default, specify the path in this parameter.
      or in the environment variable `UNITY_HUB_INSTALL_DIRECTORY`.
      The path must exclude the version number.
      ex) E:\Unity\
    required: false
    default: ''
  log-file:
    description: >
      Specify where Unity writes the Editor or Windows/Linux/OSX standalone log file.
      To output to the console, specify - for the path name.
      On Windows, specify - option to make the output go to stdout, which is not the console by default.
    required: false
    default: '-'
  additional-arguments:
    description: >
      Specify additional required arguments.
    required: false
    default: ''
  export-method:
    description: >
      Method used to export the archive.
      Valid values are: app-store, validation, ad-hoc, package, enterprise, development, developer-id and mac-application
    required: false
    default: 'development'
  include-bitcode:
    description: >
      Should the ipa file include bitcode?
      Defaults to false.
      Required for iOS builds.
    required: false
    default: false
  include-symbols:
    description: >
      Should the ipa file include symbols?
      Defaults to false.
      Required for iOS builds.
    required: false
    default: false
  strip-swift-symbols:
    description: >
      If set to true, it will truncate symbols from the Swift library in the IPA file,
      reducing the size of the IPA file.
    required: false
    default: true
  provisioning-profile-base64:
    description: ''
    required: false
    default: ''
  provisioning-profile-uuid:
    description: >
      Specify the UUID of the provisioning profile.
      Required for iOS builds.
    required: false
    default: ''
  provisioning-profile-name:
    description: >
      Specify the Name of the provisioning profile.
      Required for iOS builds.
    required: false
    default: ''
  provisioning-profile-type:
    description: >
      Specify the type of provisioning profile.
      Required for iOS builds.
      If omitted, Automatic is set.
      Valid values are: Automatic, Development, Distribution
    required: false
    default: 'Automatic'
  team-id:
    description: >
      The ID of your Developer Portal team if you're in multiple teams.
      Required for iOS builds.
    required: false
    default: ''
  keystore:
    description: >
      Specify the path to the keystore file.
      If a custom keystore is used, it must be specified; however, if it is included in the project settings in advance, it need not be specified.
      If you use a custom keystore, you must specify `keystore-password`, `keystore-alias`, and `keystore-alias-password`.
      Used during Android build.
    required: false
    default: ''
  keystore-base64:
    description: >
      Specifies Base64 data for the keystore.
      If you do not specify a file path in `keystore`, you must specify this parameter.
      Also, if this value is specified, the value of `keystore` is ignored.
      Used during Android build.
    required: false
    default: ''
  keystore-password:
    description: >
      Specify the password for the keystore.
      If a custom keystore is used, it must be specified.
      Used during Android build.
    required: false
    default: ''
  keystore-alias:
    description: >
      Specifies the name of the keystore alias.
      If a custom keystore is used, it must be specified.
      Used during Android build.
    required: false
    default: ''
  keystore-alias-password:
    description: >
      Specify the password for the keystore alias.
      If a custom keystore is used, it must be specified.
      Used during Android build.
    required: false
    default: ''
  temporary-directory:
    description: >
      Specify a temporary folder for the Xcode project files that Unity outputs during iOS build.
      No change is required unless there is a specific reason.
    required: false
    default: ${{ runner.temp }}/temp
outputs:
  output-path:
    description: 'Path of the output binary'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "box"
  color: "orange"