name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 🔄 Checkout to the branch
        uses: actions/checkout@v5

      - name: 🍏 Set up Node.js version
        uses: actions/setup-node@v4

      - name: ⚙️ npm install and build
        run: npm run build
